In [1]:
import numpy as np

In [2]:
array = np.array(range(5))

In [3]:
array

array([0, 1, 2, 3, 4])

In [4]:
array_2d = np.array([range(5), range(5)])

array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [5]:
array.shape

(5,)

In [6]:
array_2d.shape

(2, 5)

In [7]:
array.size

5

In [8]:
array_2d.shape

(2, 5)

In [9]:
array_2d.T.shape

(5, 2)

In [10]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [11]:
array.ndim

1

In [12]:
array_2d.ndim

2

In [13]:
array.dtype

dtype('int64')

In [14]:
array_2d.dtype

dtype('int64')

In [15]:
np.array(['I', 'love', 'Python'])

array(['I', 'love', 'Python'], dtype='<U6')