In [1]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [2]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [10]:
(inventory / 2).dtype

dtype('float64')

In [16]:
price = (rng.random(11) * 10)

price

array([6.43244661, 2.60207067, 7.19744365, 6.92208678, 3.87672115,
       0.78089194, 2.66579834, 8.87031369, 0.23196529, 5.23281865,
       6.29510999])

In [23]:
price = (rng.random(10) * 10).round(2)

price

array([8.11, 2.09, 5.61, 6.63, 8.26, 9.11, 1.5 , 9.06, 4.9 , 0.04])

In [24]:
(price * inventory).sum()

2705.23

In [25]:
inventory_list = list(inventory)

In [26]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [27]:
inventory_list + 2

TypeError: can only concatenate list (not "int") to list

In [28]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [29]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [30]:
[x * y for x, y in zip(inventory_list, price)]

[316.28999999999996,
 81.50999999999999,
 521.73,
 570.18,
 396.48,
 419.05999999999995,
 72.0,
 271.8,
 53.900000000000006,
 2.2800000000000002]